### ISSUE TITLE
Asking for old data

### ISSUE THREAD

**Issue by MichaelHopfengaertner** [MichaelHopfengaertner/openbadge#2]
Why does the badge kicks the remote BLE-device out, when it asks for old data?

**Comment by MichaelHopfengaertner** [comment]
It was an timeout issue. The timeout was 6 seconds, and is only resetted when data from the badge to the remote is sent. When asking for very old data, the back-stepping cost a lot of time (and could exceed this 6 seconds), especially when the data-request command comes not directly after connect, or another previous command, the badge has not even 6 seconds time for it.

I changed it to the following:
Increased the timeout to 15secs and reset the timeout also when a packet is received.

**Comment by OrenLederman** [comment]
Ready for testing?

**Comment by OrenLederman** [comment]
Also, and alternative approach would be to update the timeout in long operations. But that would mess up the code, right?

**Comment by OrenLederman** [comment]
Just checking - this is ready for testing, right?

**Comment by OrenLederman** [comment]
Fixed in this commit https://github.com/MichaelHopfengaertner/openbadge/commit/3596dd6967b4d64eb0d0b483c81edd10e9ed6ca4

**Comment by MichaelHopfengaertner** [comment]
Yup it's ready for testing.

**Comment by MichaelHopfengaertner** [comment]
The mess up wouldn't be that high. But then we have again some more dependencies between different modules (storer and sender), but I think this is ok.

I add this one to the nice to have list.

**Comment by OrenLederman** [comment]
We can close this issue
